name: Build for GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - uses: actions/checkout@v2

      # Use Yarn cache if exists.
      - id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cach dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn build:PROD

      # GitHub Pages publishes files in the docs directory.
      - run: mv dist docs

      - name: Push built assets
        run: |
          git config --global user.name 'ryym'
          git config --global user.email 'ryym.64@gmail.com'
          git add docs
          git commit -m 'Build on push'
          git push -f origin @:built
